# Generated by Django 5.0.7 on 2024-10-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('primary_address', models.CharField(max_length=255)),
                ('secondary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_master',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=255)),
                ('part_description', models.CharField(max_length=255)),
                ('order_quantity', models.CharField(max_length=50)),
                ('order_mode', models.CharField(choices=[('credit', 'Credit'), ('advanced', 'Advanced')], max_length=10)),
                ('order_value', models.FloatField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('verified_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('dispatch_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'order_transaction',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=255)),
                ('part_description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'part_master',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransactionImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('order_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='asset.ordertransaction')),
            ],
            options={
                'db_table': 'order_transaction_image',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InwardTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('part_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inward_transactions', to='asset.partmaster')),
            ],
            options={
                'db_table': 'inward_transaction',
                'ordering': ['id'],
            },
        ),
    ]
