# Generated by Django 5.0.6 on 2024-11-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertransaction',
            options={'verbose_name': 'Order Transaction', 'verbose_name_plural': 'Order Transactions'},
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='dispatch_status',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='order_mode',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='order_value',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='verified_status',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='amount_for_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.partmaster'),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
