# Generated by Django 5.0.7 on 2024-10-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_customermaster_ordertransaction_partmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='credit_limit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
