# Generated by Django 5.0.7 on 2024-10-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_customermaster_credit_limit_customermaster_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='credit_limit',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
