# Generated by Django 5.0.6 on 2024-11-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_usermaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermaster',
            old_name='company_address',
            new_name='delivery_address',
        ),
    ]
