# Generated by Django 5.0.6 on 2024-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_orderplacedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacedtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplacedtransaction',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplacedtransaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplacedtransaction',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
