# Generated by Django 5.0.6 on 2024-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_orderplacedtransaction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
    ]
