# Generated by Django 5.0.6 on 2024-11-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_rename_company_address_customermaster_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermaster',
            old_name='expiration_date',
            new_name='credit_days',
        ),
    ]
