# Generated by Django 5.0.6 on 2024-11-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_rename_expiration_date_customermaster_credit_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
