# Generated by Django 5.0.6 on 2024-11-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoactionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=200)),
                ('location_address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
        ),
    ]
