# Generated by Django 5.0.6 on 2024-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_customermaster_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partmaster',
            name='part_number',
        ),
        migrations.AddField(
            model_name='partmaster',
            name='uom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
