# Generated by Django 5.0.6 on 2024-11-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_loactionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardtransaction',
            name='locationmaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.loactionmaster'),
        ),
    ]
