# Generated by Django 5.0.6 on 2024-11-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_remove_partmaster_part_number_partmaster_uom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inwardtransaction',
            name='part_master_id',
        ),
        migrations.AddField(
            model_name='inwardtransaction',
            name='part_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inwardtransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inwardtransaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
