# Generated by Django 5.0.6 on 2024-11-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_inwardtransaction_part_master_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardtransaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
