# Generated by Django 5.0.6 on 2024-12-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_customermaster_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
