# Generated by Django 5.0.6 on 2024-11-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolepermission',
            name='permission',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userrolepermission',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
