# Generated by Django 4.2 on 2024-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_customermaster_used_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='dispatch_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='invoice_by',
            field=models.IntegerField(null=True),
        ),
    ]
