# Generated by Django 5.0.6 on 2024-11-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_userprofile_status'),
        ('asset', '0002_summa'),
        ('asset', '0003_userprofile_delete_customuser'),
        ('asset', '0013_alter_userrolepermission_permission_and_more'),
    ]

    operations = [
    ]
