# Generated by Django 5.0.6 on 2024-11-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_merge_20241117_1106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='summa',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
