# Generated by Django 5.0.6 on 2024-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_orderheader_dispatch_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
