# Generated by Django 4.2 on 2024-12-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_orderheader_delivery_address_alter_partmaster_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='SampleForm',
        ),
        migrations.AlterField(
            model_name='orderattachmenttransaction',
            name='order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='asset.orderheader'),
        ),
        migrations.AlterField(
            model_name='orderattachmenttransaction',
            name='verified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='asset.orderheader'),
        ),
    ]
