# Generated by Django 5.0.6 on 2024-12-20 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_alter_customermaster_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='asset.orderheader'),
        ),
    ]
