# Generated by Django 5.0.6 on 2024-12-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_alter_ordertransaction_order_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermaster',
            name='used_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
