# Generated by Django 5.0.6 on 2024-12-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_alter_customermaster_used_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaster',
            name='allocated_stock',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
