# Generated by Django 5.0.6 on 2024-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_alter_partmaster_allocated_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaster',
            name='stock',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
