# Generated by Django 5.0.6 on 2024-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_alter_partmaster_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='balance_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='reamining_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
