# Generated by Django 5.0.6 on 2024-12-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_customermaster_balance_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermaster',
            name='balance_limit',
        ),
        migrations.RemoveField(
            model_name='ordertransaction',
            name='reamining_paid_amount',
        ),
    ]
