# Generated by Django 4.2.2 on 2025-01-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_einvoiceheader_einvoicetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoicetransaction',
            name='ItemList',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
