# Generated by Django 4.2.2 on 2025-01-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0027_einvoicetransaction_itemlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='einvoicetransaction',
            old_name='e_invoice_header_id',
            new_name='e_invoice_header',
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200, null=True)),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.orderheader')),
            ],
            options={
                'db_table': 'request_header',
                'ordering': ['-id'],
            },
        ),
    ]
