# Generated by Django 4.2.2 on 2025-02-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0028_rename_e_invoice_header_id_einvoicetransaction_e_invoice_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmaster',
            name='hsn_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
