# Generated by Django 4.2.2 on 2025-02-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0030_customermaster_additional_address1_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='cgst_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='cgst_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='igst_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='igst_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='sgst_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='sgst_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='total_tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
