# Generated by Django 4.2.2 on 2025-02-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_orderheader_cgst_amount_orderheader_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='delivery_address_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='delivery_address_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='delivery_address_state_code',
            field=models.IntegerField(null=True),
        ),
    ]
