# Generated by Django 4.2.2 on 2025-02-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0033_remove_customermaster_status_customermaster_addrbnm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderheader',
            name='buyer_order_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='buyer_order_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='delivery_note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='delivery_note_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='dispatch_document_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='dispatched_through',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='other_references',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderheader',
            name='terms_of_delivery',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
