# Generated by Django 4.2.2 on 2025-02-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0034_orderheader_buyer_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoiceheader',
            name='einvoice_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='einvoicetransaction',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderattachmenttransaction',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
