# Generated by Django 4.2.2 on 2025-02-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0036_orderheader_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='location_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.loactionmaster'),
        ),
    ]
