# Generated by Django 4.2.2 on 2025-02-11 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0038_alter_orderheader_location_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, null=True)),
                ('total_quantity', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('location_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.loactionmaster')),
                ('part_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.partmaster')),
            ],
            options={
                'db_table': 'inward_header',
                'ordering': ['id'],
            },
        ),
    ]
