# Generated by Django 4.2.2 on 2025-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0039_inwardheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaster',
            name='allocated_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
