# Generated by Django 4.2.2 on 2025-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0041_alter_customermaster_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmaster',
            name='part_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
