# Generated by Django 4.2.2 on 2025-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0042_partmaster_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='AddlDocDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='BuyerDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='DocDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='EwbDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='ExpDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='ItemList',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='PayDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='RefDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='SellerDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='TranDtls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='einvoicetransaction',
            name='ValDtls',
            field=models.JSONField(null=True),
        ),
    ]
